# SPDX-FileCopyrightText: 2020-2026 Akseli Mansikkamäki
# SPDX-License-Identifier: GPL-3.0-or-later

import sys
import operator

from copy import deepcopy

import numpy as np

from ouluspin._fortran import fortran_utils as fu

from ouluspin import tensors
from ouluspin import result_table



class PseudoSpinBasis:
    """A class to construct and store the definition of the basis states of a
    multi-site pseudospin operator. The basis states are of the general form
    
        |S0,M0> (x) |S1,M1> (x) ...

    where S0 and M0 are the pseudospin and its projection for site 0, S1 and M1
    are the pseudospin and its projection for site 1 etc. The symbol (x) stands
    for tensor product.

    NOTE!!! All angular momentum quantum numbers are given as multiplets of two in order to treat
            half-integer angular momenta as integer numbers.

    Arguments
    ---------
    pseudospin_list : list of int
        List of integers defining the pseudospins for each spin site.
    
    Optional arguments
    ------------------

    Attributes
    ----------
    pseudospin_list : list of int
        List of integers defining the pseudospins for each spin site.
    n_basis : int
        The total number of basis states.
    n_sites : int
        The total number of spin sites.
    n_states_per_site : list of int
        A list of values corresponing to the total number of local states corresponding
        to each spin site.
    basis_state_list : list of list of tuple of int
        A list structure containing the basis state lists. It consists of three nested
        structures:
            - A list containing the actual basis states.
                - A list consisting of tuples corresponding to each spin site.
                    - A tuple of the type S,M containing the values of the pseudospin and
                      its projection corresponding to a given spin site.
    local_state_index_list : list of list of int
        A list containg a list of ints for each basis state. The list contains unique
        identification indices for each local pseudospin state corresponding to a give
        spin site.
        
    Private methods
    ---------------
    __construct_basis() : void
        Construct the basis and store it as an attribute.
    __construct_local_state_index_list() : void
        Index each local state corresponding to a give pseudospin
        state at a spin site, and construct a list of lists which
        contain the local state indices of each basis state.

    Public methods
    --------------
    construct_fortran_pseudospin_arrays() : array of int32, array of int32
        Construct and return the S and M value NumPy arrays with dimensions
        n_basis x n_sites used by the Fortran routines in construction of the operator
        matrices.
    basis_state_label(basis_state) : list of float
        Return a human-readable label of the basis state i.
    basis_state_label_header() : list of str
        Return a human-readable header for the basis state labels.
    basis_state_inner_product(i,j) : vector of int32
        Construct a vector with elements either one or zero for each
        spin site depending on whether the inner product of the basis
        states i and j for that site is one or zero.
    basis_table() : ResultTable
        Return a human-readable table of the basis states.
    conjugate_state_list() : list of list of int
        Return a list that pairs basis states as time-reversal conjugates. This is
        mostly intended for analysis purposes. The list is structured as
        [[i,j],[k,l],...], where i,j,k,l are basis state indices. The pairs 
        [i,j] define a pair of basis states that are Kramers' conjugates. Note that
        if the system is a non-Kramers system, then the states listed are not
        time-reversal conjugates but rather just states with opposite projections
        of angular momentum. Also in the case of non-Kramers systems there will
        be a state with zero angular momentum projection which does not have
        a Kramers conjugate state.
    conjugate_state_table() : ResultTable
        Return a human-readable table of the list generated by the
        conjugate_state_list() method.
    phase_matrix_list() : list of array of int32
        Construct and return a list of matrices with one matrix for each spin
        site in the system. The matrix elements have a value of 1 if the matrix
        element of the raising operator S_+ has a non-zero value between those
        states for that specific spin site, and zero otherwise.
    unitary_part_of_time_reversal_operator() : array of float64
        Return a matrix representation of the unitary part U of the time reversal
        operator.

    Class methods
    -------------
    run_tests(print_output=True) : boolean
        Initiate the class and run a set of internal tests. Return True if all
        tests passed.
    """
    
    def __construct_basis(self):
        """Construct the basis and store it as an attribute."""
        self.basis_state_list = []

        # First construct the basis just for the first site.
        S = self.pseudospin_list[0]
        for M in range(-S,S+2,2):
            self.basis_state_list.append([(S,M)])

        # Recursively append each site to the basis state list.
        for i in range(1,self.n_sites):
            S = self.pseudospin_list[i]
            new_basis_list = []
            old_basis_list = deepcopy(self.basis_state_list)
            self.basis_state_list = []
            
            for M in range(-S,S+2,2):
                new_basis_list.append((S,M))

            for old_basis_state in old_basis_list:
                for new_basis_tuple in new_basis_list:
                    new_basis_state = deepcopy(old_basis_state)
                    new_basis_state.append(new_basis_tuple)
                    self.basis_state_list.append(new_basis_state)


    def __construct_local_state_index_list(self):
        """Index each local state corresponding to a give pseudospin
        state at a spin site, and construct a list of lists which
        contain the local state indices of each basis state.
        """
        local_pseudospin_state_list = []
        for a in range(0,self.n_sites):
            local_pseudospin_state_list.append([])
            S = self.pseudospin_list[a]

            for M in range(-S,S+2,2):
                local_pseudospin_state_list[a].append(M)

        self.local_state_index_list = []
        for i in range(0,self.n_basis):
            tmp_list = []
            for a in range(0,self.n_sites):
                M = self.basis_state_list[i][a][1]
                j = local_pseudospin_state_list[a].index(M)

                tmp_list.append(j)

            self.local_state_index_list.append(tmp_list)
        
        

    def basis_state_label_header(self):
        """Return the column headers of the basis state labels, i.e. the
        list ['S_0','M_0','S_1','M_1',...] with one pair of headers per
        spin site. Used as a part of the column headers of the result
        tables that label their rows by basis states.
        """
        header_list = []
        for i in range(0,self.n_sites):
            header_list.append("S_" + str(i))
            header_list.append("M_" + str(i))

        return header_list


    def basis_state_label(self,basis_state):
        """Return the label of a basis state as a list of the values of the
        local spin S and its projection M of each spin site, i.e. the list
        [S_0,M_0,S_1,M_1,...]. Used as the leading cells of the rows of the
        result tables that label their rows by basis states.
        """
        label_list = []
        for basis_tuple in basis_state:
            label_list.append(basis_tuple[0]/2)
            label_list.append(basis_tuple[1]/2)

        return label_list

    
    def basis_state_inner_product(self,i,j):
        """Construct a vector with elements either one or zero for each
        spin site depending on whether the inner product of the basis
        states i and j for that site is one or zero.
        """
        inner_product_vector = np.zeros(self.n_sites, dtype=np.int32)
        
        for a in range(0,self.n_sites):
            if self.basis_state_list[i][a] == self.basis_state_list[j][a]:
                inner_product_vector[a] = 1
            else:
                inner_product_vector[a] = 0

        return inner_product_vector


    def construct_fortran_pseudospin_arrays(self):
        """Construct and return the S and M value NumPy arrays with dimensions
        n_basis x n_sites used by the Fortran routines in construction of the operator
        matrices.
        """
        S_array = np.zeros((self.n_basis,self.n_sites), dtype=np.int32)
        for basis_index in range(0,self.n_basis):
            for site_index in range(0,self.n_sites):
                S_array[basis_index][site_index] = self.basis_state_list[basis_index][site_index][0]
        
        M_array = np.zeros((self.n_basis,self.n_sites), dtype=np.int32)
        for basis_index in range(0,self.n_basis):
            for site_index in range(0,self.n_sites):
                M_array[basis_index][site_index] = self.basis_state_list[basis_index][site_index][1]

        return S_array, M_array
        

    def basis_table(self):
        """Return a table of the basis states as an instance of ResultTable.
        Each row contains the index of the basis state in the full basis,
        the indices of the local states of the individual spin sites and
        the local spins and their projections labelling the state.
        """
        column_headers = ['State']
        for a in range(0,self.n_sites):
            column_headers.append('Site ' + str(a))
        column_headers.extend(self.basis_state_label_header())

        # The state indices are integers and the spins and their
        # projections are printed as half-integers.
        formats = (1 + self.n_sites)*[None] + 2*self.n_sites*['.1f']

        rows = []
        for i in range(0,self.n_basis):
            row = [i]
            for j in range(0,self.n_sites):
                row.append(self.local_state_index_list[i][j])
            row.extend(self.basis_state_label(self.basis_state_list[i]))

            rows.append(row)

        return result_table.ResultTable(rows,
                                        column_headers=column_headers,
                                        title="BASIS STATES",
                                        notes="The site columns give the index of the local state of each spin site.",
                                        formats=formats,
                                        table_type='basis_states')

    
    def conjugate_state_list(self):
        """Return a list that pairs basis states as time-reversal conjugates. This is
        mostly intended for analysis purposes. The list is structured as
        [[i,j],[k,l],...], where i,j,k,l are basis state indices. The pairs 
        [i,j] define a pair of basis states that are Kramers' conjugates. Note that
        if the system is a non-Kramers system, then the states listed are not
        time-reversal conjugates but rather just states with opposite projections
        of angular momentum. Also in the case of non-Kramers systems there will
        be a state with zero angular momentum projection which does not have
        a Kramers conjugate state.
        """
        conjugate_state_list = []
        spent_state_list = []
        for i in range(0,self.n_basis):
            current_state = self.basis_state_list[i]
            conjugate_state = deepcopy(current_state)

            current_state_projection_list = []
            conjugate_state_projection_list = []
            only_zeros = True

            for state_tuple in current_state:
                current_state_projection_list.append(state_tuple[1])
                conjugate_state_projection_list.append(-state_tuple[1])
                if state_tuple[1] != 0:
                    only_zeros = False

            if only_zeros:
                conjugate_state_list.append([i])
            else:
                for j in range(0,self.n_basis):
                    other_state = self.basis_state_list[j]
                    other_state_projection_list = []
                    for state_tuple in other_state:
                        other_state_projection_list.append(state_tuple[1])

                    if not j in spent_state_list:
                        if other_state_projection_list == conjugate_state_projection_list:
                            spent_state_list.append(i)
                            spent_state_list.append(j)

                            conjugate_state_list.append([i,j])
                            break

        return conjugate_state_list

    
    def conjugate_state_table(self):
        """Return a table of the list generated by the conjugate_state_list()
        method as an instance of ResultTable. Each row contains a pair of
        basis states that are Kramers conjugates of each other, both given
        by their index and by the local spins and their projections. A
        state without a conjugate partner leaves the second half of the row
        empty.
        """
        conjugate_state_list = self.conjugate_state_list()

        state_headers  = ['State'] + self.basis_state_label_header()
        column_headers = state_headers + ['Conjugate'] \
                         + self.basis_state_label_header()
        formats        = 2*([None] + 2*self.n_sites*['.1f'])

        rows = []
        for pair in conjugate_state_list:
            row = [pair[0]] + self.basis_state_label(self.basis_state_list[pair[0]])

            if len(pair) == 2:
                row += [pair[1]] \
                       + self.basis_state_label(self.basis_state_list[pair[1]])
            else:
                # A state with a vanishing projection of the angular
                # momentum on every site has no conjugate partner.
                row += (1 + 2*self.n_sites)*[None]

            rows.append(row)

        return result_table.ResultTable(rows,
                                        column_headers=column_headers,
                                        title="LIST OF KRAMERS' CONJUGATE PAIRS IN THE BASIS STATES",
                                        formats=formats,
                                        table_type='basis_states')


    def unitary_part_of_time_reversal_operator(self):
        """Return a matrix representation of the unitary part U of the time
        reversal operator. The operator U is defined so that

            T = U . K
    
        is the operator of time-reversal when K is the anti-unitary operator of
        complex conjugation.
        """
        U = np.zeros((self.n_basis,self.n_basis), dtype=np.float64)

        conjugate_state_list = self.conjugate_state_list()

        for conjugate_pair in conjugate_state_list:
            if len(conjugate_pair) == 1:
                # A self-conjugate state (all projections zero):
                # T|S,0> = (-1)^S |S,0> for each site.
                i = conjugate_pair[0]

                phase_ii = 0
                for k in range(0,self.n_sites):
                    phase_ii += self.basis_state_list[i][k][0]

                if phase_ii % 2 != 0:
                    print("ERROR in PseudoSpinBasis.")
                    print("Error: Phase in unitary part of the time-reversal operator is not integer.")
                    print("Error termination.")
                    sys.exit(1)

                U[i][i] = (-1)**(phase_ii//2)
            else:
                i = conjugate_pair[0]
                j = conjugate_pair[1]

                phase_ij = 0
                phase_ji = 0

                for k in range(0,self.n_sites):
                    phase_ij += self.basis_state_list[j][k][0] - self.basis_state_list[j][k][1]
                    phase_ji += self.basis_state_list[i][k][0] - self.basis_state_list[i][k][1]

                if (phase_ij % 2 != 0) or (phase_ji % 2 != 0):
                    print("ERROR in PseudoSpinBasis.")
                    print("Error: Phase in unitary part of the time-reversal operator is not integer.")
                    print("Error termination.")
                    sys.exit(1)

                U[i][j] = (-1)**(phase_ij//2)
                U[j][i] = (-1)**(phase_ji//2)

        return U


    def phase_matrix_list(self):
        """Construct and return a list of matrices with one matrix for each spin
        site in the system. The matrix elements have a value of 1 if the matrix
        element of the raising operator S_+ has a non-zero value between those
        states for that specific spin site, and zero otherwise.
        """
        M_list = []
        for k in range(0,self.n_sites):
            M = np.zeros((self.n_basis,self.n_basis)).astype(int)

            for i in range(0,self.n_basis):
                for j in range(0,self.n_basis):
                    M1 = self.basis_state_list[i][k][1]
                    M2 = self.basis_state_list[j][k][1]
                        
                    if (M1 + 2 == M2):
                        tmp_M = 1
                    else:
                        tmp_M = 0

                    for l in range(0,self.n_sites):
                        M1 = self.basis_state_list[i][l][1]
                        M2 = self.basis_state_list[j][l][1]

                        if (l != k) and (M1 != M2):
                            tmp_M = 0
                            break
                        
                    M[i][j] += tmp_M
                    
            M_list.append(deepcopy(M))

        return M_list


    def __repr__(self):
        """Return a human-readable table of the basis states."""
        return str(self.basis_table())


    def __eq__(self, other):
        """Check the equality of two bases by comparing their pseudospin lists."""
        if not isinstance(other, PseudoSpinBasis):
            print("ERROR in PseudoSpinBasis.")
            print("Error: An instance of PseudoSpinBasis can only be compared to another instance of the same class.")
            print("Error termination.")
            sys.exit(1)

        return self.basis_state_list == other.basis_state_list

    
    def __init__(self, pseudospin_list):
        """Upon class initiation, construct the basis states and store them as an
        attribute.
        """
        self.pseudospin_list = pseudospin_list
        
        self.n_sites = len(self.pseudospin_list)

        self.__construct_basis()

        self.n_basis = len(self.basis_state_list)

        self.__construct_local_state_index_list()

        self.n_states_per_site = []
        for pseudospin in iter(self.pseudospin_list):
            self.n_states_per_site.append(pseudospin + 1)


    @classmethod
    def run_tests(cls, print_output=True):
        """Initiate the class and run a set of tests on the class constructor
        and the class methods. Return True if all tests passed and False
        otherwise.

        Optional arguments
        ------------------
        print_output : boolean
            Whether to print the outcome of each test. Default is True.
        """
        from ouluspin import _debug as debug_output

        result_list = []
        def check(test_name,condition):
            result_list.append(debug_output.test_check('PseudoSpinBasis',test_name,
                                                       condition,print_output))

        # A two-site basis with S = 1/2 and S = 1.
        basis = cls([1,2])
        check('basis dimensions',
              (basis.n_basis == 6) and (basis.n_sites == 2)
              and (basis.n_states_per_site == [2,3]))
        check('basis ordering',
              (basis.basis_state_list[0] == [(1,-1),(2,-2)])
              and (basis.basis_state_list[-1] == [(1,1),(2,2)]))

        S_array, M_array = basis.construct_fortran_pseudospin_arrays()
        check('fortran pseudospin arrays',
              (S_array.shape == (6,2)) and np.all(S_array[:,0] == 1)
              and (M_array[0][0] == -1) and (M_array[-1][1] == 2))

        check('inner product of a state with itself',
              np.all(basis.basis_state_inner_product(0,0) == 1))
        check('inner product of orthogonal states',
              np.all(basis.basis_state_inner_product(0,5) == 0))

        check('equality operator', basis == cls([1,2]))
        check('basis table renders', len(str(basis.basis_table())) > 0)

        # Time-reversal machinery: the conjugate state list must cover all
        # states, and the unitary part U must be orthogonal with
        # U*U = -1 for a Kramers system and U*U = +1 for a non-Kramers one.
        conjugate_list = basis.conjugate_state_list()
        state_indices = sorted([i for pair in conjugate_list for i in pair])
        check('conjugate state list covers all states',
              state_indices == list(range(0,basis.n_basis)))

        basis_kramers = cls([1])
        U = basis_kramers.unitary_part_of_time_reversal_operator()
        check('U orthogonal for a Kramers system',
              np.allclose(np.dot(U,U.T),np.identity(2)))
        check('U*U = -1 for a Kramers system',
              np.allclose(np.dot(U,U),-np.identity(2)))

        basis_non_kramers = cls([2,2])
        U = basis_non_kramers.unitary_part_of_time_reversal_operator()
        check('U orthogonal for a non-Kramers system',
              np.allclose(np.dot(U,U.T),np.identity(9)))
        check('U*U = +1 for a non-Kramers system',
              np.allclose(np.dot(U,U),np.identity(9)))

        return debug_output.test_summary('PseudoSpinBasis',result_list,print_output)



class PseudoSpinOperator:
    """A class to construct and diagonalize a multi-site pseudospin operator.

    This class is intended for operators representing physical observables. Thus, the operator
    is assumed as Hermitian. This will not be tested, and if this is not the case, the class
    will produce spurious results.

    Throughout the class it will be assumed that the eigenvalues are ordered from smallest to
    the largest value.

    NOTE!!! All angular momentum quantum numbers are given as multiples of two in order to treat
            half-integer angular momenta as integer numbers.

    Arguments
    ---------
    basis : PseudoSpinBasis
        An instance of PseudoSpinBasis containing the basis states and the values
        of the pseudospins of different sites.
    tensor_list : list of IwaharaChibotaruSphericalTensor
        A list of spherical tensor operators used in construction of the operator
        matrix. Each tensor must correspond to the same number of spin sites.
    units : EnergyUnitSystem
        An instance of EnergyUnitSystem containing the energy for output purposes.

    Optional argumets
    -----------------
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation. Default is True.
    store_operator_matrix : boolean
        Whether to store a matrix representation of the operator as an attribute. Default
        is False.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.
    eigenvalue_print_limit : float or None
        In the printing of eigenvalues and eigenvectors, the eigenvalues and the respective
        eigenvectors will only be printed if hte eigenvalue is equal to or less than this
        value. The default value is None in which case this option will be ignored. This is
        argument is especially important if a large number of eigenvectors are stored and
        printed as the eigenvector table string can grow exceedingly large and consume
        vast amouts of memory.

    Attributes
    ----------
    basis : PseudoSpinBasis
        An instance of PseudoSpinBasis containing the basis states and the values
        of the pseudospins of different sites.
    units : EnergyUnitSystem
        An instance of EnergyUnitSystem containing the energy for output purposes.
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation.
    store_operator_matrix : boolean
        Whether to store a matrix representation of the operator as an attribute.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.
    eigenvalue_print_limit : float or None
        In the printing of eigenvalues and eigenvectors, the eigenvalues and the respective
        eigenvectors will only be printed if hte eigenvalue is equal to or less than this
        value. The default value is None in which case this option will be ignored. This
        argument is especially important if a large number of eigenvectors are stored and
        printed as the eigenvector table string can grow exceedingly large and consume
        vast amouts of memory.
    tensor : IwaharaChibotaruSphericalTensor
        The tensor used in construction of the operator matrix. This tensor is
        constructed as a sum of the tensors given in the class arguments.
    matrix : array of complex128
        Matrix representation of the operator.
    n_sites : int
        The number of spin sites in the system.
    n_ranks : int
        The number of ranks, i.e., the length of rank_list.
    eigenvectors : array of complex128
        Eigenvector matrix. The columns of the matrices correspond to the eigenvectors.
    eigenvalues : list of float64
        A list of the eigenvalues.
    n_basis : int
        The total number of pseudospin basis states.

    Private methods
    ---------------
    __diagonalize() : void
        Construct the matrix, diagonalize it and return the eigenvalues and eigenvectors.
        The construction and diagonalization will be handled by fortran_utils.

    Public methods
    --------------
    construct_matrix(only_triangle=False) : array of complex128
        Contruct the matrix representation of the operator corresponding and return it.
    eigenvalue_table(eigenvalue_print_limit=None) : ResultTable
        Return a human-readable table of just the eigenvalues. The argument can be used
        to override the default class instance value for the print limit.
    eigenvector_table(eigenvalue_print_limit=None, print_threshold=None) : ResultTable
        Return a human-readable table of the eigenvalues and eigenvectors. The argument
        can be used to override the default class instance value for the print limit.

    Class methods
    -------------
    from_vector_operator(basis,vector,mixed_tensor_list,units,...)
        Construct a pseudospin operator by contracting a Cartesian vector with mixed
        Cartesian--spherical tensors given as a list of instances of
        MixedCartesianIwaharaChibotaruSphericalTensor. This is mostly intended for the
        construction of the Zeeman operator from the magnetic-field vector and the
        g tensor. The optional arguments are the same as those of the class constructor.
    run_tests(print_output=True) : boolean
        Initiate the class and run a set of internal tests. Return True if all
        tests passed.
    """

    def __diagonalize(self):
        """Construct the matrix, diagonalize it and return the eigenvalues and eigenvectors.
        The construction and diagonalization will be handled by fortran_utils.

        In order to properly call the diagonalize_general_iwahara_operator Fortran
        subroutine, the different quantum numbers need to be re-ordered into NumPy arrays.
        """
        self.eigenvalues  = []
        self.eigenvectors = []

        parameters = self.tensor.parameter_list
        k_array, q_array = self.tensor.fortran_rank_arrays()

        lowest_eigenvalue = None

        S_array, M_array = self.basis.construct_fortran_pseudospin_arrays()

        self.eigenvalues, self.eigenvectors = fu.iwahara_utils.diagonalize_general_iwahara_operator_matrix(S_array,M_array,k_array,q_array,parameters)

        # Translate eigenvalues so that the lowest eigenvalue is zero.
        if self.translate_eigenvalues:
            lowest_eigenvalue = min(self.eigenvalues)
            self.eigenvalues = self.eigenvalues - lowest_eigenvalue

        self.eigenvalues = list(self.eigenvalues)


    def construct_matrix(self,only_triangle=False):
        """Contruct the matrix representation of the operator corresponding and return it."""
        k_array, q_array = self.tensor.fortran_rank_arrays()
        S_array, M_array = self.basis.construct_fortran_pseudospin_arrays()
        parameters       = self.tensor.parameter_list

        return fu.iwahara_utils\
                 .construct_general_iwahara_operator_matrix(S_array,M_array,
                                                            k_array,q_array,parameters,
                                                            only_triangle)


    def __print_limit(self, eigenvalue_print_limit):
        """Return the eigenvalue print limit used by the table methods. The
        argument overrides the value stored in the instance, and the value
        None means that no limit is applied.
        """
        if not eigenvalue_print_limit == None:
            return eigenvalue_print_limit
        elif not self.eigenvalue_print_limit == None:
            return self.eigenvalue_print_limit
        else:
            return None


    def eigenvalue_table(self, eigenvalue_print_limit=None):
        """Return a table of just the eigenvalues as an instance of
        ResultTable. Each row contains the index of a state and its
        eigenvalue. When the operator matrix was not diagonalized, an empty
        table stating this is returned.

        Optional arguments
        ------------------
        eigenvalue_print_limit : float or None
            Eigenvalues above this value are not tabulated. Default is
            None, in which case the print limit stored in the instance is
            used.
        """
        if not self.diagonalize_operator_matrix:
            return result_table.ResultTable([],
                                            title="LIST OF EIGENVALUES",
                                            notes="No eigenvalues available.",
                                            table_type='eigenvalues')

        print_limit = self.__print_limit(eigenvalue_print_limit)

        rows = []
        for i in range(0,self.n_basis):
            if not print_limit == None:
                if self.eigenvalues[i] > print_limit:
                    break
            rows.append([i,self.eigenvalues[i]])

        return result_table.ResultTable(rows,
                                        column_headers=['Index','Eigenvalue'],
                                        title="LIST OF EIGENVALUES",
                                        formats=[None,'.3f'],
                                        table_type='eigenvalues')


    def eigenvector_table(self, eigenvalue_print_limit=None, print_threshold=None):
        """Return a table of the eigenvalues and eigenvectors as an instance
        of ResultTable. The eigenvectors are tabulated one below the other
        in sections labelled by the corresponding eigenvalue; each row of a
        section contains the index of a basis state, the local spins and
        their projections labelling it and the real part, the imaginary
        part and the squared modulus of the coefficient of that basis state
        in the eigenvector. When the operator matrix was not diagonalized,
        an empty table stating this is returned.

        Optional arguments
        ------------------
        eigenvalue_print_limit : float or None
            Eigenvectors of states with an eigenvalue above this value are
            not tabulated. Default is None, in which case the print limit
            stored in the instance is used.
        print_threshold : float or None
            Basis states whose squared coefficient is below this value are
            not tabulated. Default is None, in which case all the basis
            states are tabulated.
        """
        if not self.diagonalize_operator_matrix:
            return result_table.ResultTable([],
                                            title="EIGENVECTORS",
                                            notes="No eigenvectors available.",
                                            table_type='eigenvectors')

        print_limit = self.__print_limit(eigenvalue_print_limit)

        column_headers = ['Index'] + self.basis.basis_state_label_header() \
                         + ['Re(C)','Im(C)','|C|^2']
        formats        = [None] + 2*self.basis.n_sites*['.1f'] + 3*['.6f']

        rows = []

        for i in range(0,self.n_basis):
            if not print_limit == None:
                if self.eigenvalues[i] > print_limit:
                    break

            rows.append("Eigenvalue {0:.3f}".format(self.eigenvalues[i]))

            for j in range(0,self.n_basis):
                basis_state = self.basis.basis_state_list[j]
                C = self.eigenvectors[j][i]

                if print_threshold is not None and abs(C)**2 < print_threshold:
                    continue

                rows.append([j] + self.basis.basis_state_label(basis_state)
                            + [C.real,C.imag,abs(C)**2])

        return result_table.ResultTable(rows,
                                        column_headers=column_headers,
                                        title="EIGENVECTORS",
                                        formats=formats,
                                        table_type='eigenvectors')


    def __repr__(self):
        """Return a human-readable summary of the operator."""
        return str(self.eigenvalue_table())

    
    def __init__(self, basis, tensor_list, units,
                 diagonalize_operator_matrix=True,
                 store_operator_matrix=False,
                 translate_eigenvalues=False,
                 eigenvalue_print_limit=None):
        """Diagonalize the operator and store the eigenvectors
        and eigenvalues as attributes.
        """
        self.basis = basis
        self.units = units

        self.diagonalize_operator_matrix = diagonalize_operator_matrix
        self.store_operator_matrix       = store_operator_matrix
        self.translate_eigenvalues       = translate_eigenvalues
        self.eigenvalue_print_limit      = eigenvalue_print_limit

        self.n_sites = self.basis.n_sites
        self.n_basis = self.basis.n_basis
        
        for tensor in tensor_list:
            if not tensor.n_sites == self.n_sites:
                print("ERROR in PseudoSpinOperator.")
                print("Error: Inconsistent number of spin sites in the tensors.")
                print("Error termination.")
                sys.exit(1)

        self.tensor = sum(tensor_list)
        self.n_ranks = self.tensor.n_ranks

        if self.diagonalize_operator_matrix:
            self.__diagonalize()

        if self.store_operator_matrix:
            self.matrix = self.construct_matrix()


    @classmethod
    def from_vector_operator(cls, basis, vector, mixed_tensor_list, units,
                             diagonalize_operator_matrix=True,
                             store_operator_matrix=False,
                             translate_eigenvalues=False,
                             eigenvalue_print_limit=None):
        """Construct a pseudospin operator by contracting a Cartesian vector with mixed
        Cartesian--spherical tensors. This is mostly intended for the construction of
        the Zeeman operator from the magnetic-field vector and the g tensor given as a
        MixedCartesianIwaharaChibotaruSphericalTensor, but can be used for any vector
        quantity and list of MixedCartesianIwaharaChibotaruSphericalTensor instances.

        Coordinate frame convention: the Cartesian vector and the mixed
        tensors must be expressed in the SAME coordinate frame
        (conventionally the principal magnetic axis frame of the system).
        A field vector given in another frame, e.g. the input frame of an
        ab initio calculation, must be rotated into the frame of the
        tensors before calling this method.

        The mixed tensors given in the list are first summed up similar to the
        summation of the tensor list in the class constructor. The summed mixed
        Cartesian--spherical tensor is then contracted with the vector, and the
        resulting scalar spherical tensor is used as an input for the class
        constructor. For the Zeeman operator the construction corresponds to

            H_Zeeman = sum_{a,k1,q1,k2,q2,...} B_a * g^a_{k1,q1,k2,q2,...}
                                                   * O_{k1,q1}(S_1) * O_{k2,q2}(S_2) ...

        where B_a is a Cartesian component of the magnetic-field vector.

        Arguments
        ---------
        basis : PseudoSpinBasis
            An instance of PseudoSpinBasis containing the basis states and the values
            of the pseudospins of different sites.
        vector : array of float64
            The Cartesian vector (for example, the magnetic-field vector) that is
            contracted with the Cartesian index of the mixed tensors.
        mixed_tensor_list : list of MixedCartesianIwaharaChibotaruSphericalTensor
            A list of mixed Cartesian--spherical tensors. Each tensor must correspond
            to the same number of spin sites.
        units : EnergyUnitSystem
            An instance of EnergyUnitSystem containing the energy for output purposes.

        The optional arguments are the same as those of the class constructor.
        """
        for mixed_tensor in iter(mixed_tensor_list):
            if not isinstance(mixed_tensor,
                              tensors.MixedCartesianIwaharaChibotaruSphericalTensor):
                print("ERROR in PseudoSpinOperator.")
                print("Error: The tensors must be instances of MixedCartesianIwaharaChibotaruSphericalTensor.")
                print("Error termination.")
                sys.exit(1)

        summed_tensor     = sum(mixed_tensor_list)
        contracted_tensor = summed_tensor.contract_with_vector(vector)

        return cls(basis, [contracted_tensor], units,
                   diagonalize_operator_matrix=diagonalize_operator_matrix,
                   store_operator_matrix=store_operator_matrix,
                   translate_eigenvalues=translate_eigenvalues,
                   eigenvalue_print_limit=eigenvalue_print_limit)


    @classmethod
    def run_tests(cls, print_output=True):
        """Initiate the class and run a set of tests on the class constructor
        and the class methods. Return True if all tests passed and False
        otherwise.

        Optional arguments
        ------------------
        print_output : boolean
            Whether to print the outcome of each test. Default is True.
        """
        from ouluspin import units
        from ouluspin import _debug as debug_output

        result_list = []
        def check(test_name,condition):
            result_list.append(debug_output.test_check('PseudoSpinOperator',test_name,
                                                       condition,print_output))

        tmp_units = units.EnergyUnitSystem('wavenumber')

        # A Heisenberg dimer of two S = 1/2 spins: H = J*S_A.S_B with
        # J = 10 cm^-1 gives a singlet ground state and a triplet at J.
        J = 10.0
        heisenberg = tensors.IwaharaChibotaruSphericalTensor\
                            .from_two_site_isotropic_operator(J,1,1)
        basis = PseudoSpinBasis([1,1])
        operator = cls(basis,[heisenberg],tmp_units,
                       translate_eigenvalues=True,
                       store_operator_matrix=True)

        check('Heisenberg dimer singlet-triplet gap',
              np.allclose(operator.eigenvalues,[0.0,J,J,J]))
        check('operator matrix is Hermitian',
              np.allclose(operator.matrix,operator.matrix.conj().T))
        check('operator matrix is traceless',
              abs(np.trace(operator.matrix)) < 1.0e-10)
        check('construct_matrix consistent with stored matrix',
              np.allclose(operator.construct_matrix(),operator.matrix))

        # A single-site Zeeman-type splitting: X*S_z for S = 1/2 gives the
        # translated eigenvalues 0 and X.
        zeeman = tensors.IwaharaChibotaruSphericalTensor\
                        .from_one_site_cartesian_operator(2.0,'z',1)
        operator_z = cls(PseudoSpinBasis([1]),[zeeman],tmp_units,
                         translate_eigenvalues=True)
        check('Zeeman splitting of a spin-1/2',
              np.allclose(operator_z.eigenvalues,[0.0,2.0]))

        # from_vector_operator: contraction of a general mixed
        # Cartesian--spherical tensor with a Cartesian vector. The operator
        # matrix must equal sum_ab v_a*g_ab*S_b.
        pseudospin = 3   # S = 3/2
        S_ops = debug_output.spin_matrices(pseudospin)
        g_matrix = np.array([[ 2.1, 0.3,-0.4],
                             [ 0.1, 1.7, 0.2],
                             [-0.4, 0.5, 2.4]])
        v = np.array([0.3,-1.2,0.8])
        mixed_tensor = tensors.MixedCartesianIwaharaChibotaruSphericalTensor\
                              .from_one_site_cartesian_tensor(g_matrix,pseudospin)
        operator_v = cls.from_vector_operator(PseudoSpinBasis([pseudospin]),v,
                                              [mixed_tensor],tmp_units,
                                              diagonalize_operator_matrix=False,
                                              store_operator_matrix=True)
        M_ref = sum(v[a]*g_matrix[a][b]*S_ops[b]
                    for a in range(0,3) for b in range(0,3))
        check('from_vector_operator matches contracted spin matrices',
              np.allclose(operator_v.matrix,M_ref))

        # The mixed tensors of the list must be summed before the
        # contraction: two half tensors must give the same operator as one
        # full tensor.
        operator_halves = cls.from_vector_operator(PseudoSpinBasis([pseudospin]),v,
                                                   [0.5*mixed_tensor,0.5*mixed_tensor],
                                                   tmp_units,
                                                   diagonalize_operator_matrix=False,
                                                   store_operator_matrix=True)
        check('from_vector_operator sums the mixed tensors',
              np.allclose(operator_halves.matrix,M_ref))

        # The Zeeman operator of an isotropic spin-1/2 moment with g = 2 in
        # a field along z: the translated eigenvalues are 0 and 2.
        mixed_isotropic = tensors.MixedCartesianIwaharaChibotaruSphericalTensor\
                                 .from_one_site_isotropic_operator(2.0,1)
        operator_zeeman = cls.from_vector_operator(PseudoSpinBasis([1]),
                                                   np.array([0.0,0.0,1.0]),
                                                   [mixed_isotropic],tmp_units,
                                                   translate_eigenvalues=True)
        check('from_vector_operator Zeeman splitting of a spin-1/2',
              np.allclose(operator_zeeman.eigenvalues,[0.0,2.0]))

        check('eigenvalue table renders',
              len(str(operator.eigenvalue_table(eigenvalue_print_limit=1000.0))) > 0)
        check('eigenvector table renders',
              len(str(operator.eigenvector_table(eigenvalue_print_limit=1000.0,
                                                 print_threshold=0.01))) > 0)
        check('the eigenvalue table is a ResultTable',
              isinstance(operator.eigenvalue_table(),result_table.ResultTable))
        check('the eigenvalue table has one row per state',
              len(operator.eigenvalue_table().rows) == operator.n_basis)
        check('the eigenvalue print limit drops the higher states',
              len(operator_zeeman.eigenvalue_table(eigenvalue_print_limit=1.0).rows) == 1)
        check('the eigenvector table groups the states into sections',
              len([row for row in operator_zeeman.eigenvector_table().rows
                   if isinstance(row,str)]) == operator_zeeman.n_basis)
        check('the eigenvector print threshold drops the small coefficients',
              len([row for row in
                   operator_zeeman.eigenvector_table(print_threshold=0.5).rows
                   if isinstance(row,list)]) == operator_zeeman.n_basis)

        return debug_output.test_summary('PseudoSpinOperator',result_list,print_output)



class PseudoSpinVectorOperator:
    """A class to store the instance of PseudoSpinOperator associated with a set of
    operators transforming as a vector operator. This class is mostly intended as
    a simple interface to handle a list of instances of PseudoSpinOperator.

    Arguments
    ---------
    basis : PseudoSpinBasis
        An instance of PseudoSpinBasis containing the basis states and the values
        of the pseudospins of different sites.
    mixed_tensor_list : list of MixedCartesianIwaharaChibotaruSphericalTensor
        A list of mixed Cartesian--spherical tensors used in construction of the
        operator matrices. The operator of each Cartesian component is constructed
        from the corresponding Cartesian components of all mixed tensors in the
        list (i.e., the components are used in the constructor of
        PseudoSpinOperator). Each tensor must correspond to the same number of
        spin sites.
    units : EnergyUnitSystem
        An instance of EnergyUnitSystem containing the energy for output purposes.

    Optional argumets
    -----------------
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation. Default is True.
    store_operator_matrix : boolean
        Whether to store a matrix representation of the operator as an attribute. Default
        is False.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.
    eigenvalue_print_limit : float or None
        In the printing of eigenvalues and eigenvectors, the eigenvalues and the respective
        eigenvectors will only be printed if hte eigenvalue is equal to or less than this
        value. The default value is None in which case this option will be ignored. This is
        argument is especially important if a large number of eigenvectors are stored and
        printed as the eigenvector table string can grow exceedingly large and consume
        vast amouts of memory.

    Attributes
    ----------
    basis : PseudoSpinBasis
        An instance of PseudoSpinBasis containing the basis states and the values
        of the pseudospins of different sites.
    units : EnergyUnitSystem
        An instance of EnergyUnitSystem containing the energy for output purposes.
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation. Default is True.
    store_operator_matrix : boolean
        Whether to store a matrix representation of the operator as an attribute. Default
        is False.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.
    n_operators : int
        The number of components in the vector operator. This is always three, as the
        components correspond to the Cartesian components of the mixed
        Cartesian--spherical tensors.
    operator_list : list of PseudoSpinOperator
        The components of the vector operator in the order x, y, z.

    Private methods
    ---------------

    Public methods
    --------------
    matrix_list() : list of array of complex128
        Return a list of matrix representations of the different components of the vector
        operator.
    eigenvalue_table(eigenvalue_print_limit=None) : ResultTable
        Return a human-readable table of just the eigenvalues. The argument can be used
        to override the default class instance value for the print limit.
    eigenvector_table(eigenvalue_print_limit=None, print_threshold=None) : ResultTable
        Return a human-readable table of the eigenvalues and eigenvectors. The argument
        can be used to override the default class instance value for the print limit.

    Class methods
    -------------
    run_tests(print_output=True) : boolean
        Initiate the class and run a set of internal tests. Return True if all
        tests passed.
    """

    def matrix_list(self):
        """Return a list of matrix representations of the different components of the
        vector operator.
        """
        if not self.store_operator_matrix:
            print("ERROR in PseudoSpinVectorOperator.")
            print("Error: Matrix list requested but matrices are not stored.")
            print("Error termination.")
            sys.exit(1)
        
        tmp_list = []
        for i in range(0,self.n_operators):
            tmp_list.append(self.operator_list[i].matrix)

        return tmp_list
    

    def __component_table(self, component_table_list, title):
        """Combine the tables of the individual Cartesian components of the
        vector operator, given as a list of ResultTable instances in the
        order of the components, into a single ResultTable in which the
        components form consecutive sections. The tables of the components
        share their column structure, which is taken from the first one.
        """
        index_to_component = {0 : "x", 1 : "y", 2 : "z"}

        rows = []
        for i in range(0,len(component_table_list)):
            rows.append("Vector operator component {0}"
                        .format(index_to_component.get(i,str(i))))
            rows.extend(component_table_list[i].rows)

        if len(component_table_list) > 0:
            column_headers = component_table_list[0].column_headers
            formats        = component_table_list[0].formats
            table_type     = component_table_list[0].table_type
        else:
            column_headers = None
            formats        = None
            table_type     = None

        if len(column_headers) == 0:
            column_headers = None

        return result_table.ResultTable(rows,
                                        column_headers=column_headers,
                                        title=title,
                                        formats=formats,
                                        table_type=table_type)


    def eigenvalue_table(self, eigenvalue_print_limit=None):
        """Return a table of just the eigenvalues of the three Cartesian
        components of the vector operator as an instance of ResultTable.
        The components are tabulated one below the other in sections; the
        rows are those of the eigenvalue table of the individual components.

        Optional arguments
        ------------------
        eigenvalue_print_limit : float or None
            Eigenvalues above this value are not tabulated. Default is
            None, in which case the print limit stored in the instance is
            used.
        """
        component_table_list = []
        for i in range(0,self.n_operators):
            component_table_list.append(
                self.operator_list[i]
                    .eigenvalue_table(eigenvalue_print_limit=eigenvalue_print_limit))

        return self.__component_table(component_table_list,
                                      "LIST OF EIGENVALUES OF THE VECTOR OPERATOR COMPONENTS")


    def eigenvector_table(self, eigenvalue_print_limit=None, print_threshold=None):
        """Return a table of the eigenvalues and eigenvectors of the three
        Cartesian components of the vector operator as an instance of
        ResultTable. The components are tabulated one below the other in
        sections; the rows are those of the eigenvector table of the
        individual components.

        Optional arguments
        ------------------
        eigenvalue_print_limit : float or None
            Eigenvectors of states with an eigenvalue above this value are
            not tabulated. Default is None, in which case the print limit
            stored in the instance is used.
        print_threshold : float or None
            Basis states whose squared coefficient is below this value are
            not tabulated. Default is None, in which case all the basis
            states are tabulated.
        """
        component_table_list = []
        for i in range(0,self.n_operators):
            component_table_list.append(
                self.operator_list[i]
                    .eigenvector_table(eigenvalue_print_limit=eigenvalue_print_limit,
                                       print_threshold=print_threshold))

        return self.__component_table(component_table_list,
                                      "EIGENVECTORS OF THE VECTOR OPERATOR COMPONENTS")


    def __repr__(self):
        """Return a human-readable summary of the vector operator."""
        return str(self.eigenvalue_table())

    
    def __init__(self, basis, mixed_tensor_list, units,
                 diagonalize_operator_matrix=True,
                 store_operator_matrix=False,
                 translate_eigenvalues=False,
                 eigenvalue_print_limit=None):
        """Diagonalize the operator and store the eigenvectors and eigenvalues as
        attributes.
        """
        self.basis = basis
        self.units = units
        self.diagonalize_operator_matrix = diagonalize_operator_matrix
        self.store_operator_matrix = store_operator_matrix
        self.translate_eigenvalues = translate_eigenvalues

        for mixed_tensor in iter(mixed_tensor_list):
            if not isinstance(mixed_tensor,
                              tensors.MixedCartesianIwaharaChibotaruSphericalTensor):
                print("ERROR in PseudoSpinVectorOperator.")
                print("Error: The tensors must be instances of MixedCartesianIwaharaChibotaruSphericalTensor.")
                print("Error termination.")
                sys.exit(1)

        self.n_operators = 3

        self.operator_list = []

        for k in range(0,self.n_operators): # Cartesian index
            tensor_list = []
            for mixed_tensor in iter(mixed_tensor_list):
                tensor_list.append(mixed_tensor.component_list[k])

            self.operator_list.append(PseudoSpinOperator(self.basis, tensor_list, self.units,
                                                         diagonalize_operator_matrix=self.diagonalize_operator_matrix,
                                                         store_operator_matrix=self.store_operator_matrix,
                                                         translate_eigenvalues=self.translate_eigenvalues,
                                                         eigenvalue_print_limit=eigenvalue_print_limit))


    @classmethod
    def run_tests(cls, print_output=True):
        """Initiate the class and run a set of tests on the class constructor
        and the class methods. Return True if all tests passed and False
        otherwise.

        Optional arguments
        ------------------
        print_output : boolean
            Whether to print the outcome of each test. Default is True.
        """
        from ouluspin import units
        from ouluspin import _debug as debug_output

        result_list = []
        def check(test_name,condition):
            result_list.append(debug_output.test_check('PseudoSpinVectorOperator',
                                                       test_name,condition,print_output))

        tmp_units  = units.EnergyUnitSystem('wavenumber')
        pseudospin = 3   # S = 3/2

        # A spin vector operator given as a mixed Cartesian--spherical tensor.
        mixed_tensor = tensors.MixedCartesianIwaharaChibotaruSphericalTensor\
                              .from_one_site_isotropic_operator(1.0,pseudospin)

        vector_operator = cls(PseudoSpinBasis([pseudospin]),[mixed_tensor],
                              tmp_units,
                              diagonalize_operator_matrix=False,
                              store_operator_matrix=True)

        check('number of components', vector_operator.n_operators == 3)

        matrix_list = vector_operator.matrix_list()
        check('matrix list dimensions',
              (len(matrix_list) == 3) and (matrix_list[0].shape == (4,4)))

        # The components must obey the angular momentum commutation relation
        # [S_x,S_y] = i*S_z.
        commutator = np.dot(matrix_list[0],matrix_list[1]) \
                     - np.dot(matrix_list[1],matrix_list[0])
        check('commutator [S_x,S_y] = i*S_z',
              np.allclose(commutator,1.0j*matrix_list[2]))

        squared = sum(np.dot(matrix,matrix) for matrix in matrix_list)
        S = pseudospin/2.0
        check('S^2 = S(S+1)*identity',
              np.allclose(squared,S*(S + 1.0)*np.identity(4)))

        check('eigenvalue table renders',
              len(str(vector_operator.eigenvalue_table())) > 0)

        return debug_output.test_summary('PseudoSpinVectorOperator',
                                         result_list,print_output)



class GeneralOperatorMatrix:
    """A class to store a matrix representation of an operator in an arbitary
    basis and carry operations on it. The main purpose of this class is to store
    operator matrices in a convenient way so that they can be used in the construction
    of pseudospin operators.

    The operator is assumed Hermitian!

    Arguments
    ---------
    matrix : array of complex128
        A matrix representation of the operator.

    Optional arguments
    ------------------
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation. Default is True.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.

    Attributes
    ----------
    matrix : array of complex128
        A matrix representation of the operator.
    eigenvalues : list of float64
        The eigenvalues. Only available if the matrix has been diagonalized.
    eigenvectors : array of complex128
        The eigenvector matrix. Only available if the matrix has been diagonalized.
    n_basis : int
        The dimension of the matrix.
    diagonalize_operator_matrix : boolean
        Whether the operator matrix was diagonalized upon class initiation.
    translate_eigenvalues : boolean
        Whether the eigenvalues were translated so that the lowest one is
        zero.

    Private methods
    ---------------
    __diagonalize()
        Diagonalize the operator matrix, store the eigenvalues and
        eigenvectors as attributes and translate the eigenvalues if
        requested.

    Public methods
    --------------
    eigenvalue_table(print_limit=None) : ResultTable
        Return a human-readable table of just the eigenvalues.

    Class methods
    -------------
    run_tests(print_output=True) : boolean
        Initiate the class and run a set of internal tests. Return True if all
        tests passed.
    """

    def __diagonalize(self):
        """Diagonalize the matrix and store the eigenvales and eigenvectors as
        attributes. The diagonalization will be handled by fortran_utils.
        """
        self.eigenvalues, self.eigenvectors = fu.matrix_utils.external_diagonalize_complex_matrix(self.matrix)

        self.eigenvalues = list(self.eigenvalues)

        if self.translate_eigenvalues:
            lowest_eigenvalue = min(self.eigenvalues)
            for i in range(0,len(self.eigenvalues)):
                self.eigenvalues[i] = self.eigenvalues[i] - lowest_eigenvalue

                    
    def eigenvalue_table(self, print_limit=None):
        """Return a table of just the eigenvalues as an instance of
        ResultTable. Each row contains the index of a state and its
        eigenvalue. When the operator matrix was not diagonalized, an empty
        table stating this is returned.

        Optional arguments
        ------------------
        print_limit : float or None
            Eigenvalues above this value are not tabulated. Default is
            None, in which case all the eigenvalues are tabulated.
        """
        if not self.diagonalize_operator_matrix:
            return result_table.ResultTable([],
                                            title="LIST OF EIGENVALUES",
                                            notes="No eigenvalues available.",
                                            table_type='eigenvalues')

        rows = []
        for i in range(0,len(self.eigenvalues)):
            if not print_limit == None:
                if self.eigenvalues[i] > print_limit:
                    break
            rows.append([i,self.eigenvalues[i]])

        return result_table.ResultTable(rows,
                                        column_headers=['Index','Eigenvalue'],
                                        title="LIST OF EIGENVALUES",
                                        formats=[None,'.3f'],
                                        table_type='eigenvalues')


    def __repr__(self):
        """Return a human-readable summary of the operator matrix."""
        return str(self.eigenvalue_table())


    def __add__(self, other):
        """Return a new instance with the sum of the two operator matrices."""
        if other is None:
            return deepcopy(self)

        elif not isinstance(other, GeneralOperatorMatrix):
                print("ERROR in GeneralOperatorMatrix.")
                print("ERROR: Operator matrices can only be added to other operator matrices.")
                print("Error termination.")
                sys.exit(1)

        else:
            if not self.n_basis == other.n_basis:
                print("ERROR in GeneralOperatorMatrix.")
                print("ERROR: Cannot add two operators with different basis dimensions.")
                print("Error termination.")
                sys.exit(1)

            copy_of_self = deepcopy(self)

            copy_of_self.matrix = self.matrix + other.matrix
            return copy_of_self

        
    def __mul__(self, other):
        """Multiply by a number or take the matrix product with another instance and return the result as a new instance."""
        if isinstance(other, (int, float, complex)):
            copy_of_self = deepcopy(self)
            copy_of_self.matrix = other * self.matrix
            return copy_of_self

        elif isinstance(other, GeneralOperatorMatrix):
            copy_of_self = deepcopy(self)
            copy_of_self.matrix = np.dot(self.matrix,other.matrix)
            return copy_of_self

        else:
            print("ERROR in GeneralOperatorMatrix.")
            print("ERROR: Unrecognized object in multiplication.")
            print("Error termination.")
            sys.exit(1)
            

    def __init__(self, matrix,
                 diagonalize_operator_matrix=False,
                 translate_eigenvalues=False):
        """Check Hermicity and store the matrix as an attribute. If diagonalization
        is requested, do it.
        """
        self.matrix = matrix
        self.diagonalize_operator_matrix = diagonalize_operator_matrix
        self.translate_eigenvalues = translate_eigenvalues

        if not len(matrix.shape) == 2:
            print("ERROR in GeneralOperatorMatrix.")
            print("Error: The matrix is not two-dimensional.")
            print("Error termination.")
            sys.exit(1)
            
        if not matrix.shape[0] == matrix.shape[1]:
            print("ERROR in GeneralOperatorMatrix.")
            print("Error: The matrix is not square.")
            print("Error termination.")
            sys.exit(1)
            
        if not np.allclose(matrix,matrix.conj().T):
            print("ERROR in GeneralOperatorMatrix.")
            print("Error: The matrix is not Hermitean.")
            print("Error termination.")
            sys.exit(1)

        self.n_basis = self.matrix.shape[0]

        if self.diagonalize_operator_matrix:
            self.__diagonalize()


    @classmethod
    def run_tests(cls, print_output=True):
        """Initiate the class and run a set of tests on the class constructor
        and the class methods. Return True if all tests passed and False
        otherwise.

        Optional arguments
        ------------------
        print_output : boolean
            Whether to print the outcome of each test. Default is True.
        """
        from ouluspin import _debug as debug_output

        result_list = []
        def check(test_name,condition):
            result_list.append(debug_output.test_check('GeneralOperatorMatrix',
                                                       test_name,condition,print_output))

        matrix = np.array([[2.0,1.0-1.0j],
                           [1.0+1.0j,3.0]], dtype=np.complex128)
        operator = cls(matrix,
                       diagonalize_operator_matrix=True,
                       translate_eigenvalues=True)

        check('basis dimension', operator.n_basis == 2)

        eigenvalues_reference = np.linalg.eigvalsh(matrix)
        eigenvalues_reference = eigenvalues_reference - min(eigenvalues_reference)
        check('eigenvalues match a reference diagonalization',
              np.allclose(operator.eigenvalues,eigenvalues_reference))

        check('eigenvectors diagonalize the matrix',
              np.allclose(np.dot(operator.eigenvectors.conj().T,
                                 np.dot(matrix,operator.eigenvectors))
                          - np.diag(np.diag(np.dot(operator.eigenvectors.conj().T,
                                                   np.dot(matrix,operator.eigenvectors)))),
                          0.0))

        summed = operator + operator
        check('addition', np.allclose(summed.matrix,2.0*matrix))
        check('addition with None', np.allclose((operator + None).matrix,matrix))

        product = operator*operator
        check('matrix multiplication', np.allclose(product.matrix,np.dot(matrix,matrix)))
        scaled = operator*2.0
        check('scalar multiplication', np.allclose(scaled.matrix,2.0*matrix))

        check('eigenvalue table renders', len(str(operator.eigenvalue_table())) > 0)

        return debug_output.test_summary('GeneralOperatorMatrix',
                                         result_list,print_output)



class GeneralVectorOperatorMatrix:
    """A class to store a set of matrices corresponding to the different components
    of a vector operator. This class is mostly intended as a simple interace for
    handling a set of operator components.

    The components of the operator are assumed Hermitian!

    Arguments
    ---------
    matrix_list : list of array of complex128
        A matrix representations of the operator components.

    Optional arguments
    ------------------
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation. Default is True.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.

    Attributes
    ----------
    diagonalize_operator_matrix : boolean
        Whether to diagonalize the operator upon class initiation. Default is True.
    translate_eigenvalues : boolean
        Whether to add a constant shift to all eigenvalues so that the lowest eigenvalue
        is equal to zero. This makes sense when the operator is the Hamiltonian, but
        should not be used in other cases.
    operator_list : list of GeneralOperatorMatrix
        List of the operator components.
    n_operators : int
        The number of components in the vector operator. This is usually three as the
        most common type of a vector operator is a Cartesian vector operator.
    n_basis : int
        Dimension of the operator matrices.

    Private methods
    ---------------

    Public methods
    --------------
    matrix_list() : list of array of complex128
        Return a list of matrix representations of the different components of the vector
        operator.

    Class methods
    -------------
    run_tests(print_output=True) : boolean
        Initiate the class and run a set of internal tests. Return True if all
        tests passed.
    """

    def matrix_list(self):
        """Return a list of matrix representations of the different components of the
        vector operator.
        """
        tmp_list = []
        for i in range(0,self.n_operators):
            tmp_list.append(self.operator_list[i].matrix)

        return tmp_list


    def eigenvalue_table(self, print_limit=None):
        """Return a table of the eigenvalues of the three Cartesian
        components of the vector operator as an instance of ResultTable.
        The components are tabulated one below the other in sections; the
        rows are those of the eigenvalue table of the individual components.

        Optional arguments
        ------------------
        print_limit : float or None
            Eigenvalues above this value are not tabulated. Default is
            None, in which case all the eigenvalues are tabulated.
        """
        index_to_component = {0 : "x", 1 : "y", 2 : "z"}

        rows           = []
        column_headers = None
        formats        = None

        for i in range(0,self.n_operators):
            component_table = self.operator_list[i].eigenvalue_table(print_limit=print_limit)

            rows.append("Vector operator component {0}"
                        .format(index_to_component.get(i,str(i))))
            rows.extend(component_table.rows)

            if i == 0 and len(component_table.column_headers) > 0:
                column_headers = component_table.column_headers
                formats        = component_table.formats

        return result_table.ResultTable(rows,
                                        column_headers=column_headers,
                                        title="LIST OF EIGENVALUES OF THE VECTOR OPERATOR COMPONENTS",
                                        formats=formats,
                                        table_type='eigenvalues')


    def __repr__(self):
        """Return a human-readable summary of the vector operator matrices."""
        return str(self.eigenvalue_table())
    

    def __init__(self, matrix_list,
                 diagonalize_operator_matrix=False,
                 translate_eigenvalues=False):
        """Construct the list of instances of GeneralOperatorMatrix."""

        self.diagonalize_operator_matrix = diagonalize_operator_matrix
        self.translate_eigenvalues = translate_eigenvalues

        self.n_operators = len(matrix_list)

        self.operator_list = []

        for matrix in iter(matrix_list):
            self.operator_list.append(GeneralOperatorMatrix(matrix,
                                                            diagonalize_operator_matrix=self.diagonalize_operator_matrix,
                                                            translate_eigenvalues=self.translate_eigenvalues))

        self.n_basis = self.operator_list[0].n_basis

        if (not self.n_basis == self.operator_list[1].n_basis) or (not self.n_basis == self.operator_list[2].n_basis):
            print("ERROR in GeneralVectorOperatorMatrix.")
            print("Error: Inconsistent operator dimensions.")
            print("Error termination.")
            sys.exit(1)


    @classmethod
    def run_tests(cls, print_output=True):
        """Initiate the class and run a set of tests on the class constructor
        and the class methods. Return True if all tests passed and False
        otherwise.

        Optional arguments
        ------------------
        print_output : boolean
            Whether to print the outcome of each test. Default is True.
        """
        from ouluspin import _debug as debug_output

        result_list = []
        def check(test_name,condition):
            result_list.append(debug_output.test_check('GeneralVectorOperatorMatrix',
                                                       test_name,condition,print_output))

        # The Cartesian components of an S = 1 spin operator.
        spin_matrix_list = debug_output.spin_matrices(2)
        vector_operator = cls(spin_matrix_list,
                              diagonalize_operator_matrix=True,
                              translate_eigenvalues=False)

        check('dimensions',
              (vector_operator.n_operators == 3) and (vector_operator.n_basis == 3))
        check('matrix list contents',
              all(np.allclose(a,b) for a, b in zip(vector_operator.matrix_list(),
                                                   spin_matrix_list)))
        check('eigenvalues of S_z',
              np.allclose(vector_operator.operator_list[2].eigenvalues,[-1.0,0.0,1.0]))
        check('string representation renders', len(str(vector_operator)) > 0)

        return debug_output.test_summary('GeneralVectorOperatorMatrix',
                                         result_list,print_output)
